site_name: Pilzkampf-Bot Doc
site_url: https://pilzkampf.github.io/bot/
site_description: Dokumentation für den Pilzkampf Bot für Pikmin Bloom

theme:
  name: material
  language: de
  logo: assets/pilzkampf_bot.png
  favilecon: assets/pilzkampf_bot.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: green
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: amber
      accent: deep orange
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
    - search.suggest
    - search.highlight
    - navigation.tracking

repo_url: https://github.com/pilzkampf/bot
repo_name: pilzkampf/bot

copyright: Copyright &copy; 2024 - 2025 Pilzkampf Bot Team

plugins:
  - i18n:
      default_language: de
      languages:
        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - Mushroom Battle: 
              - Overview: battle.md
              - Create a mushroom offer: offer-mushroom.md
              - Joining a mushroom battle: join-mushroom.md
            - Commands:
              - Overview: commands.md
              - Settings: userconfig.md
              - Timer: timer.md
              - Profile: profile.md
              - List of active battles: active.md
              - Mushroom alert: alarm.md
            - Privacy: privacy.md
            - Support: support.md
        - locale: de
          name: Deutsch
          build: true
          default: true
          nav:
            - Startseite: index.md
            - Pilzkampf: 
              - Pilzkampf Übersicht: battle.md
              - Pilzkampf erstellen: offer-mushroom.md
              - Pilzkampf beitreten: join-mushroom.md
            - Kommandos:
              - Übersicht: commands.md
              - Einstellungen: userconfig.md
              - Timer: timer.md
              - Profil: profile.md
              - Liste der aktiven Pilze: active.md
              - Pilz-Alarm: alarm.md
            - Datenschutz: privacy.md
            - Unterstützen: support.md
  - search

extra:
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/G2G5OZ8MW
    - icon: simple/telegram
      link: https://t.me/pikminpilz_bot

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: docs/includes/

extra_javascript:
  - javascripts/font-toggle.js

extra_css:
  - stylesheets/font-toggle.css
